baseURL: https://library.whitman.edu
languageCode: en-us
defaultContentLanguage: en
title: Penrose Library, Whitman College, Walla Walla, WA
theme: Penrose-cupper-hugo-theme
disqusShortname: 
enableGitInfo: true
summaryLength: 25

taxonomies:
  tag: tags

permalinks:
  post: /blog/:filename/
  pages: /:filename/

imaging:
  quality: 99

params:
  description: 
  homeMetaContent: Penrose Library, Whitman College
  # For more date formats see https://gohugo.io/functions/format/
  MatomoSiteID: 1
  CloudflareAnalytics: 4152c068e3194d95b1cf83c0e975b720
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: false
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  moveFooterToHeader: false
  customCss:
    - css/simple-tooltip.css
    - css/custom.css
  # customjs loaded in defer mode  
  customJs:
    - js/home-searchbox.js
    - js/custom.js
    - js/van11y-accessible-simple-tooltip-aria.min.js

menu:
  nav:
    - name: Database A-Z
      url: https://libguides.whitman.edu/az/databases
      weight: 1
    - name: Journals
      url: https://browzine.com/libraries/3481/subjects
      weight: 2
    - name: Library Guides
      url: /guides/
      weight: 3
    - name: Library Services & FAQ
      url: /library_services/
      weight: 7
    - name: Contact Library Staff
      url: /contact_librarystaff/
      weight: 6       
    - name: Faculty Services
      url: https://libguides.whitman.edu/faculty
      weight: 13
    - name: About the Library
      url: /about_the_library/
      weight: 25
    - name: ARMINDA
      url: https://arminda.whitman.edu
      weight: 23
    - name: Course Reserves
      url: /course_reserves
      weight: 19
    - name: Archives
      url: /archives/
      weight: 5
    - name: Thesis
      url: https://libguides.whitman.edu/thesis
      weight: 21
    - name: Blog
      url: /post/
      weight: 29
- name: Accessibility Information
      url: /accessibility/
      weight: 27

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false

  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
